apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipvs-controller
rules:
- apiGroups:
  - policy
  resourceNames:
  - ipvs-controller-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
