apiVersion: v1
kind: Service
metadata:
  name: udp-ping-pong
  labels:
    app: udp-ping-pong
spec:
  type: LoadBalancer
  selector:
    app: udp-ping-pong
  ports:
  - port: 12161
    targetPort: 12161
    protocol: UDP
    name: udp
